// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvTe7fyZbgFU5AJs29j7QLARVwbZfFovs',
    appId: '1:206700597521:web:835961dd3c8f0a42a77cb0',
    messagingSenderId: '206700597521',
    projectId: 'resumebuilder-app-9b8f2',
    authDomain: 'resumebuilder-app-9b8f2.firebaseapp.com',
    storageBucket: 'resumebuilder-app-9b8f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LSS928meL-L_AeEwxhY8RWdhR-ixyqk',
    appId: '1:206700597521:android:fed6bd4851c77789a77cb0',
    messagingSenderId: '206700597521',
    projectId: 'resumebuilder-app-9b8f2',
    storageBucket: 'resumebuilder-app-9b8f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUCQq4d5AgV4Fm6aEwLrB5KKKwx_xDaKM',
    appId: '1:206700597521:ios:4223788ef3745fe6a77cb0',
    messagingSenderId: '206700597521',
    projectId: 'resumebuilder-app-9b8f2',
    storageBucket: 'resumebuilder-app-9b8f2.firebasestorage.app',
    iosBundleId: 'com.example.aiResumebuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUCQq4d5AgV4Fm6aEwLrB5KKKwx_xDaKM',
    appId: '1:206700597521:ios:4223788ef3745fe6a77cb0',
    messagingSenderId: '206700597521',
    projectId: 'resumebuilder-app-9b8f2',
    storageBucket: 'resumebuilder-app-9b8f2.firebasestorage.app',
    iosBundleId: 'com.example.aiResumebuilderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvTe7fyZbgFU5AJs29j7QLARVwbZfFovs',
    appId: '1:206700597521:web:bc2777dfbd425dffa77cb0',
    messagingSenderId: '206700597521',
    projectId: 'resumebuilder-app-9b8f2',
    authDomain: 'resumebuilder-app-9b8f2.firebaseapp.com',
    storageBucket: 'resumebuilder-app-9b8f2.firebasestorage.app',
  );
}
